dist: xenial
language: python
branches:
  only:
    - master
    - dev
    - production


python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'

install:
  - pip install codecov
script:
  - coverage run tests/test_purepy.py
after_success:
  - codecov

stages:
  - test
  - name: deploy
    if: branch = production

jobs:
  include:
    - stage: test
    - stage: deploy
      name: "Deploy"
      python: '3.7'
      script: skip
      deploy: &pypi
        provider: pypi
        user: mccartnm
        password:
          secure: DCQE0Tzn6gek87mxv4JZkQHnnxK97IDojZyV7q/xfs2F/sz8vohBJt17cH4ft7/gyFCmiHy69rXra69kxvX+2x68FDIQlzJsg2S52DpbpR448FgE/qVc3wYSxXRqeVbLY5ijPt5oLg7WqyiB1wrIBqlMROXHQjnPrA4NeitnaTIAMagF+m6MTGMAt6q2X3jg/snunnfatk+DTXYkPuFbIQ4olx3Y4knKBp4DWSyK+089Wepgs+IeCtDJqPMUfhXhR6+68+Vo1ZVvN4YMa6wdWRbLCCDpEj1Fvbc811FrkZPx3yIaiQlxho87ZxBa6ncpfY4s9brvD9LeGq59x79XCOVv0xvZgV1w3mFGFAuqWZMotbkb9Hy8kpgg6EOzRMSU2ka6AE9XL/6AAiTU/fh9neEeuqufir2H/GxaJgb/T5E2mfqvo5Jmfi+aymaPsjG/OKRjzVIeiOmq9cCkzDe1az2Or/9Vrrb3S/1UXv+HI/GE4qn8fHq8PDUusUt6dtiqUeus7OLaIAjuHie4WWGweXgWu6R2Ru9OOO7vvIQy048gEeDgYUklS/+qB/+2p1+BbYqvTtszaWpufj8KegadQyM5CRY3uMqzdntaQj6hZArHisu5hcx9CoiyVRSr8/wqIy349tw8wjhPt4318gAcvtE3q3rSq4tvf9GP1Pu0HWc=
        distributions: "sdist bdist_wheel"
        on:
          branch: production
        skip_existing: true
