dist: xenial
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
install:
  - pip install codecov
script:
  - coverage run tests/test_purepy.py
after_success:
  - codecov
branches:
  only:
    - master
    - dev
    - production
deploy:
  provider: pypi
  user: mccartnm
  password:
    secure: rC5GdVfhsLt73grwIfIH3lhFPNiHUl7URqVl7mWgQHhD7K2pwEhAJQmPIo9d2O11NB+IXqMO6tSX6EI0hpEbku6J3Er4oWNwg87RfFPT8vuoTYqqYmqKu2B2AIgLyfRmE3HocxlDAeX/2xV0osfEPZhX0AccrZEQDE0g743koQ0OSOqPErh8Byf34uws7b4aqkpZvVLdgoafciQL0Kef5xDmAY+8cF2gQtUwLtEsmaLs0rgQmpjim3KmlJEQPZydDps9GCTjGdj1yNwWR+5jQOQNCeyZ9pZ0PlXiPtkruL1F+HlWb5PiObv6sBx/bHECGc2AhS0PoZpxlq91AKVi5pbd7cw5X3oMxjEr/hNUVP9ZWjFyBT5+z6cky3Sy5h8Zu5uXKoPP3vpHslZpH+pOYgO5oXmtRsOJsFrJYTCo4OPu5Ys5qT94i0iPv6F3gEozJF24lHPMzPO6plCsulL1cLikXax02bZ2bY9ho6tbwGT68li71CWfDlMPPwlhcc/MQgxAiSvF1+heyErctU01EINpOSzaVcKn5ISVEiK7vg9Chx9kzxEqQfUOcqgDW0vncBO+mWO9LP+x4vSetRsZXCFmT+IbQ5XZEOqtkUcI/a2JSWcJLx4kJMWAhW1MGxLZBDVgsLGabMaPHRmdk51fOB8xWWEi4QxuymieoxykSnw=
  distributions: "sdist bdist_wheel"
  on:
    branch: production
  skip_existing: true