dist: xenial
language: python
branches:
  only:
    - master
    - dev
    - production


python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'

install:
  - pip install codecov
script:
  - coverage run tests/test_purepy.py
after_success:
  - codecov

stages:
  - test
  - name: deploy
    if: branch = production

jobs:
  include:
    - stage: test
    - stage: deploy
      name: "Deploy"
      script: skip
      python: '3.7'
      deploy: &pypi
        python: '3.7'
        provider: pypi
        user: mccartnm
        password:
          secure: HwWeB0dQ3b9jdJ95CQkT+nkL7RFWtnb8pStY27pPz2bTWs2SbP51dIyMJMiMpG3kVzTNQHgraIQfjf8j4FkF+YihbdKq6X7NT+Isdc7guyIa2L4uyykHRwiQKaFYfmA95kgIQgu55Gi4mf3l5OculUvfytw1pMhV4hR/1nTPEkyjcUlGKEuRC+L0BIfxS47JuDSFzLPBDDXGdEODVChyicJmTiPkKR+b+xSXE1hnoA44gLElMwpBC9JvkjumE/f2EwwPaPtktn5cnvaO0Rc/x5z+MPs9RbXgqJiKl3+PlcYCydMPGl+SSEb3fUvAYRglCBc0PmOsLr721iTXAFlePXJpYw96dUWmG7LCQi5XbPIoKKrYmitSmT5zJoXdQaTfhchcbTHmEsm/3OtO0n/HqnUE3op2SB6kQa09RiHuoDlmt5Dd9VMqaptrPCVkQI9mh704oUa9rjVxop0ePyDzPUlcMYnZJeLK65LPk1gdSfmnBppLZ/oXqORcLV1SqWfQUshVGYIwiZL52AXAPk+gvXM0kMpDeejbhqwPZpAaGtr61rj9nWkgv5uM7R7PVb/7+YuCxYo4VZW9NQHJjj+L4SS6mR2QqngAXRHAECHQf8iHNumuibnqQzwwhcbbbfNw3lRbc/vQVLlA4slFcMFQGotCRNi9YlUifIH9o2Bgp9I=
        distributions: "sdist bdist_wheel"
        on:
          branch: production
          python: '3.7'
        skip_existing: true
